name: Python Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python3 Version
        run: python3 --version
      - name: Check requests package
        run: pip show requests
      
        
