# Python Test Workflow

name: Python Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python3 Version
        run: python3 --version
      - name: Check requests package
        run: pip show requests
      - name: Get Code
        uses: actions/checkout@v6
      - name: Run code
        run: python3 api_test.py
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Build project
        run: echo "Build Python packages..."
      - name: Deploy
        run: echo "Deploy Python packages..."
